version: '3.3'
services:
    nginx:
      image: nginx:latest
      container_name: nginx
      ports:
        - target: 80
          published: 80
          protocol: tcp
      volumes:
        - type: bind
          source: ./nginx/nginx.conf
          target: /etc/nginx/nginx.conf
      depends_on:
        - client

    client:
      image: stratcastor/forum:latest
      ports:
        - target: 5000
      build: .


...

